### ISSUE TITLE
Not running properly, with error 

### ISSUE THREAD

**Issue by RobotsAreCrazy** [Sylensky/poe-hat-b#1]
Traceback (most recent call last):
  File "/usr/share/poe-hat/main.py", line 11, in <module>
    from poe_hat_b import POE_HAT_B
  File "/usr/share/poe-hat/poe_hat_b/POE_HAT_B.py", line 17, in <module>
    show.Init();
  File "/usr/share/poe-hat/poe_hat_b/SSD1306.py", line 53, in Init
    self.SendCommand(0xAE)
  File "/usr/share/poe-hat/poe_hat_b/SSD1306.py", line 44, in SendCommand
    self.bus.write_byte_data(self.addr, 0x00, cmd)
  File "/usr/local/lib/python3.10/dist-packages/smbus2/smbus2.py", line 455, in write_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error

Any idea?
On Debian 12 bookworm

**Comment by Sylensky** [comment]
Oh thanks for reporting. This error is probably due to a very outdated `smbus` library that i included for unknown reason in this line:
https://github.com/Sylensky/poe-hat-b/blob/64bf6206c139788dd3e62601433c5cb6788cb0f4/install.sh#L13
Change the `python3-smbus` to `python3-smbus2` and let me know if that fixed your issue.
